export const loanProducts = [
  {
    id: 'personal',
    name: 'Personal Loan',
    description: 'Unsecured personal loan for your financial needs',
    min_amount: 50000,
    max_amount: 1500000,
    min_tenure: 6,
    max_tenure: 60,
    interest_type: 'reducing_balance',
  },
  {
    id: 'vehicle-2w',
    name: 'Two Wheeler Loan',
    description: 'Finance your dream bike with our two wheeler loan',
    min_amount: 50000,
    max_amount: 1500000,
    min_tenure: 12,
    max_tenure: 36,
    interest_type: 'flat',
  },
  {
    id: 'vehicle-4w',
    name: 'Four Wheeler Loan',
    description: 'Finance your car with our four wheeler loan',
    min_amount: 200000,
    max_amount: 5000000,
    min_tenure: 12,
    max_tenure: 84,
    interest_type: 'reducing_balance',
  },
  {
    id: 'vehicle-ev',
    name: 'Electric Vehicle Loan',
    description: 'Special financing for electric vehicles',
    min_amount: 100000,
    max_amount: 3000000,
    min_tenure: 12,
    max_tenure: 60,
    interest_type: 'reducing_balance',
  },
  {
    id: 'gold',
    name: 'Gold Loan',
    description: 'Quick loan against your gold ornaments',
    min_amount: 10000,
    max_amount: 5000000,
    min_tenure: 3,
    max_tenure: 36,
    interest_type: 'flat',
  },
  {
    id: 'msme',
    name: 'MSME Loan',
    description: 'Business financing for Micro, Small and Medium Enterprises',
    min_amount: 100000,
    max_amount: 25000000,
    min_tenure: 12,
    max_tenure: 120,
    interest_type: 'annuity',
  },
  {
    id: 'home',
    name: 'Home Loan',
    description: 'Finance your dream home with our home loan',
    min_amount: 200000,
    max_amount: 50000000,
    min_tenure: 24,
    max_tenure: 360,
    interest_type: 'reducing_balance',
  },
  {
    id: 'mortgage',
    name: 'Mortgage Loan',
    description: 'Loan against property for your financial needs',
    min_amount: 100000,
    max_amount: 50000000,
    min_tenure: 24,
    max_tenure: 240,
    interest_type: 'reducing_balance',
  },
  {
    id: 'topup',
    name: 'Top Up Loan',
    description: 'Top up loan for existing customers',
    min_amount: 50000,
    max_amount: 2000000,
    min_tenure: 6,
    max_tenure: 60,
    interest_type: 'reducing_balance',
  },
] as const;

export type LoanProductId = typeof loanProducts[number]['id'];